# Try to find the CFITSIO libraries
# On success, defines:
#
#  CFITSIO_FOUND - CFITSIO located
#  CFITSIO_INCLUDE_DIR - Directory containing fitsio.h
#  CFITSIO_LIBRARIES - libcfitsio.so

INCLUDE(CheckLibraryExists)

IF (NOT CFITSIO_INCLUDE_DIR)
	FIND_PATH(CFITSIO_INCLUDE_DIR fitsio.h)
ENDIF (NOT CFITSIO_INCLUDE_DIR)

IF (NOT CFITSIO_LIBRARIES)
	FIND_LIBRARY(CFITSIO_LIBRARIES NAMES cfitsio)
ENDIF (NOT CFITSIO_LIBRARIES)

IF (CFITSIO_INCLUDE_DIR AND CFITSIO_LIBRARIES)
	SET(CFITSIO_FOUND TRUE )
	SET(CFITSIO_LIBRARIES )
	SET(CFITSIO_INCLUDE_DIR )

	MESSAGE(STATUS "Found CFITSIO: ${CFITSIO_LIBRARIES}")
ELSE (CFITSIO_INCLUDE_DIR AND CFITSIO_LIBRARIES)
	SET(CFITSIO_FOUND FALSE)
ENDIF (CFITSIO_INCLUDE_DIR AND CFITSIO_LIBRARIES)

